/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "The Humanoid Robotics Course Curriculum",
  "tagline": "AI Assistant with Robotics Education",
  "favicon": "img/favicon.ico",
  "url": "https://itxfatehmdkk.github.io",
  "baseUrl": "/AI-Humanoid-Robotics-text-book/",
  "organizationName": "itxfatehmdkk",
  "projectName": "AI-Humanoid-Robotics-text-book",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\Fateh Mohammad\\Desktop\\ai-course-book\\textbook-frontend\\sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/itxfatehmdkk/AI-Humanoid-Robotics-text-book/tree/main/textbook-frontend/"
        },
        "blog": false,
        "theme": {
          "customCss": "C:\\Users\\Fateh Mohammad\\Desktop\\ai-course-book\\textbook-frontend\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "🤖 The Humanoid Robotics Course",
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "📚 Course"
        },
        {
          "type": "dropdown",
          "label": "Modules 📘",
          "position": "left",
          "items": [
            {
              "label": "1️⃣ ROS 2 Fundamentals",
              "to": "/module-1-robotic-nervous-system/ros2-fundamentals"
            },
            {
              "label": "2️⃣ Digital Twin (Gazebo & Unity)",
              "to": "/module-2-digital-twin/physics-simulation-gazebo"
            },
            {
              "label": "3️⃣ AI-Robot Brain (NVIDIA Isaac)",
              "to": "/module-3-ai-brain/isaac-sim-foundations"
            },
            {
              "label": "4️⃣ Vision-Language-Action (VLA)",
              "to": "/module-4-vla/voice-to-action-whisper-ros2"
            }
          ]
        },
        {
          "href": "https://github.com/itxfatehmdkk/AI-Humanoid-Robotics-text-book",
          "label": "🐙 GitHub",
          "position": "right"
        },
        {
          "label": "💬 Chat",
          "position": "right",
          "to": "/chat"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learning Path",
          "items": [
            {
              "label": "Module 1: ROS 2 Fundamentals",
              "to": "/module-1-robotic-nervous-system/ros2-fundamentals"
            },
            {
              "label": "Module 2: Digital Twin",
              "to": "/module-2-digital-twin/physics-simulation-gazebo"
            },
            {
              "label": "Module 3: AI-Robot Brain",
              "to": "/module-3-ai-brain/isaac-sim-foundations"
            },
            {
              "label": "Module 4: Voice-to-Action",
              "to": "/module-4-vla/voice-to-action-whisper-ros2"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/itxfatehmdkk/AI-Humanoid-Robotics-text-book"
            },
            {
              "label": "ROS Community",
              "href": "https://discourse.ros.org/"
            },
            {
              "label": "Docusaurus Forum",
              "href": "https://docusaurus.io/showcase"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Report an Issue",
              "href": "https://github.com/itxfatehmdkk/AI-Humanoid-Robotics-text-book/issues"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 The Humanoid Robotics Course Curriculum. Built with Docusaurus."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
